# Generated by Django 3.2.13 on 2022-05-15 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_title', models.CharField(help_text='Mersedes Benz', max_length=150, verbose_name='Название модел')),
            ],
            options={
                'verbose_name': 'название машину',
                'verbose_name_plural': 'Название машины',
            },
        ),
        migrations.CreateModel(
            name='DriveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_drive', models.CharField(help_text='Передний,Задний,4x4', max_length=150, verbose_name='Привод Машин')),
            ],
            options={
                'verbose_name': 'Типы приводов',
            },
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuels', models.CharField(help_text='Безин,Газ,Дизел,Электомобил', max_length=150, verbose_name='Тип топлива')),
            ],
            options={
                'verbose_name': 'Типы топлива',
            },
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transmission', models.CharField(help_text='Auto', max_length=150, verbose_name='Тип коробка передача')),
            ],
            options={
                'verbose_name': 'Типы коробок передач',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.PositiveIntegerField(default=0, help_text='123456', verbose_name='Пробег')),
                ('year', models.PositiveIntegerField(default=2000, help_text='2001', verbose_name='Год выпуск')),
                ('color', models.CharField(help_text='Black', max_length=150, verbose_name='Цвет машин')),
                ('color_interior', models.CharField(help_text='Black and White', max_length=150, verbose_name='Цвет интерьера')),
                ('vin', models.CharField(help_text='ABCDEFG123', max_length=150, verbose_name='VIN номер')),
                ('engine', models.CharField(help_text='V8  4.7', max_length=150, verbose_name='Двигатель')),
                ('brand', models.ForeignKey(help_text='Mersedes', on_delete=django.db.models.deletion.CASCADE, to='cars.brand', verbose_name='Название машин')),
                ('drive_type', models.ForeignKey(help_text='Передний', on_delete=django.db.models.deletion.CASCADE, to='cars.drivetype', verbose_name='Привод машин')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_fuel_type', to='cars.fuel', verbose_name='Тип топлива')),
                ('transmission', models.ForeignKey(help_text='Auto & Stick', on_delete=django.db.models.deletion.CASCADE, to='cars.transmission', verbose_name='Тип коробка передача')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
    ]
