# Generated by Django 3.2.13 on 2022-05-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='названия компанию', max_length=255, verbose_name='Название')),
                ('logo', models.ImageField(upload_to='logo/', verbose_name='Логотип')),
                ('adress', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=50)),
                ('work_time', models.CharField(help_text='09:00 - 20:00, ПН-ПТ', max_length=100, verbose_name='Время работа')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
