# Generated by Django 3.2.13 on 2022-05-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='logo2',
            field=models.ImageField(blank=True, upload_to='logo/', verbose_name='Логотип2'),
        ),
    ]
